### PR TITLE
Introduce Cilium Cluster Mesh API Server Mock (cmapisrv-mock)

### PR DESCRIPTION
**Pull request by giorio94**
cmapisrv-mock is component which mocks the behavior of the Cilium Cluster Mesh API Server. It supports mocking a user-configurable number of clusters, each composed of a given number of nodes, endpoints, identities and services, initialized at start-up time. Subsequently, at run-time, it additionally generates insertion, update (where appropriate) and deletion churn, depending on the configured QPS values.

### CODE REVIEW

**Comment by giorio94** [comment]
Thanks!

> Can we add a [seed parameter](https://pkg.go.dev/math/rand#New) that allows us to deterministically replicate the random behavior of the mocked API server? This would allow us to repeat the results of an interesting scale test in case we want to dig into it further.

Sure, that definitely makes sense. Let me add it.

> Can you explain a bit how a scale test would work using the mocked server? If I understand correctly, it would involve observing the behavior of Cilium Agents in a single cluster responding to the load provided by the mocked cmapi server, correct? Are there specific metrics that we'd want to watch out for?

I haven't reasoned much about that yet, honestly. My high level idea would be to have a single, relatively small cluster, and set up Cilium to connect to the mocked API server, configured based on the scale we want to exercise. In terms of metrics I'd probably start with basic CPU/memory usage, and a bunch of others that we already consider in the 100 nodes scale test, to track performance improvements/regressions at much higher scales compared to it, and covering the clustermesh ingestion logic as well. Probably the easiest way would be running it in parallel with CL2 (although I haven't yet looked into the details), to handle all the scraping tasks and generate some local churn as well. Then it would nice to capture also etcd/clustermesh-related metrics, but that will likely require some extra preparation work to clean them up a bit. Does that make sense to you?

**Comment by giorio94** [comment]
> > Can we add a [seed parameter](https://pkg.go.dev/math/rand#New) that allows us to deterministically replicate the random behavior of the mocked API server? This would allow us to repeat the results of an interesting scale test in case we want to dig into it further.
> 
> Sure, that definitely makes sense. Let me add it.

I looked a bit more into this, and it wouldn't actually be enough to just set the seed to make the results reproducible, given that generators for the different clusters/resources are actually run in parallel, leading to additional non-determinism. In particular, because all extractions (random numbers, names, IP addresses) are currently performed from a single pool. The trickiest to address IMO seems the IP extraction, as that would require giving a dedicated slice to each cluster/resource combination, rather than sourcing them from a global pool (which in turn requires selecting the correct size of the pool depending on the different scale parameters). Do you think it could make sense to address this as a follow-up if the necessity arises, to avoid increasing the overall complexity in this initial phase.

**Comment by learnitall** [comment]
> Does that make sense to you?

Your ideas on how the test would work definitely make sense and SGTM. Integration with CL2 shouldn't be a problem at all, we should be able to just deploy cmapisrv-mock, start some measurements, maybe sleep for a bit, then collect and export. 

> Do you think it could make sense to address this as a follow-up if the necessity arises, to avoid increasing the overall complexity in this initial phase.
Thanks for looking into it! Makes sense to do as a follow-up. It would be a great 'nice-to-have', but not worth blocking the initial phase over or even investing too much time into TBH. If we run into an issue that we want to recreate, we can always rerun the test until we come across it again. It's not as optimal of course, but that would be fairly trivial to automate.


Side note - would the test environment more closely resemble kvstoremesh since cmapisrv-mock uses a single etcd instance?

**Comment by giorio94** [comment]
> Side note - would the test environment more closely resemble kvstoremesh since cmapisrv-mock uses a single etcd instance?

Kinda, especially from an etcd perspective. `cmapisrv-mock` uses the kvstoremesh API for convenience, as that allows to mock multiple clusters using the same etcd instance. Alternatively, it is also possible to have multiple deployments of the `cmapisrv-mock`, each mocking just a single cluster, although it is a bit more inconvenient as we cannot just scale the number of replicas (maybe we could do some tricks with statefulsets, but I haven't tried yet). 

In terms of etcd performance, the `cmapisrv-mock` is configured by default with pretty high QPS; my expectation though, is that this should not cause issues because etcd is run fully in memory to remove disk latencies, and the number of agents that connect to it is expected to be relatively low. 

That said, we could also put the real kvstoremesh in front if we wanted to test that component as well. I'm not totally sure whether it would be much useful from a testing perspective though, as its performance strongly depend on the configured QPS.

**Comment by learnitall** [comment]
Ah ok that makes sense. I'm curious in the difference between Cilium's performance when it is facing high-churn from a single etcd instance or high-churn from across multiple etcd instances. I wouldn't expect there to be a difference, but that's an assumption I'd like to collect data on at some point. What do you think?

Putting the real kvstoremesh in front would be a great test as well. In that case we could probably just mock Cilium instead :smile:

**Review by learnitall — APPROVED** [review]
Anyways, let's get this merged :partying_face:

**Comment by giorio94** [comment]
> I'm curious in the difference between Cilium's performance when it is facing high-churn from a single etcd instance or high-churn from across multiple etcd instances. I wouldn't expect there to be a difference, but that's an assumption I'd like to collect data on at some point.

Hmm, regardless of whether clustermesh or kvstoremesh is used, Cilium agents always use a different etcd client towards each cluster, hence there's no difference in terms of rate limiting from that point of view. The total amount of data to be retrieved in both cases is also similar, but definitely the distribution would be different. In classic clustermesh, we have all agents in all clusters retrieving the data for a single cluster from a given etcd instance), while with kvstoremesh all agents in a single cluster retrieve the data for all clusters from a given etcd instance. The main advantage of kvstoremesh is that it is more predictable, as it can be rate limited independently and can be tuned based on the scale of the local cluster only.

**Comment by marseel** [comment]
hmmm, Github is having some issue with verifying the sign for each commit: 
```
The base branch requires all commits to be signed
```

**Comment by giorio94** [comment]
> hmmm, Github is having some issue with verifying the sign for each commit:
> 
> ```
> The base branch requires all commits to be signed
> ```

It seems to refer to GPG/SSH signing (not the signed-off-by line), and the commits are indeed not signed. But the commits in the main branch are not signed as well, so I'm wondering if this is due to some misconfiguration.

**Comment by giorio94** [comment]
It seems due to:

image

Is this intentional?

**Pull request merged**
